package schema

import (
	"fmt"
	"strings"
)

// Statement builders shared by RestoreDDL and ChangeDDL. None of them end
// with a semicolon.

func createSchemaSQL(n Namespace, ifNotExists bool) string {
	return "CREATE SCHEMA " + ifNotExistsSQL(ifNotExists) + QuoteIdent(n.Name)
}

func createExtensionSQL(e Extension) string {
	return fmt.Sprintf("CREATE EXTENSION IF NOT EXISTS %s WITH SCHEMA %s", QuoteIdent(e.Name), QuoteIdent(e.Schema))
}

func createRoleSQL(role string) string {
	return fmt.Sprintf("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = %s) THEN CREATE ROLE %s NOLOGIN; END IF; END $$",
		QuoteLiteral(role), QuoteIdent(role))
}

// createTypeSQL creates a type. Domain checks come separately from
// domainCheckSQL so a NOT VALID check can be restored.
func createTypeSQL(t Type) string {
	switch t.Kind {
	case TypeEnum:
		labels := make([]string, len(t.Labels))
		for i, l := range t.Labels {
			labels[i] = QuoteLiteral(l)
		}
		return fmt.Sprintf("CREATE TYPE %s AS ENUM (%s)", t.ID(), strings.Join(labels, ", "))
	case TypeComposite:
		attrs := make([]string, len(t.Attributes))
		for i, a := range t.Attributes {
			attrs[i] = QuoteIdent(a.Name) + " " + a.Type
		}
		return fmt.Sprintf("CREATE TYPE %s AS (%s)", t.ID(), strings.Join(attrs, ", "))
	default:
		var b strings.Builder
		fmt.Fprintf(&b, "CREATE DOMAIN %s AS %s", t.ID(), t.BaseType)
		if t.Collation != "" {
			b.WriteString(" COLLATE " + t.Collation)
		}
		if t.Default != "" {
			b.WriteString(" DEFAULT " + t.Default)
		}
		if t.NotNull {
			b.WriteString(" NOT NULL")
		}
		return b.String()
	}
}

func domainCheckSQL(t Type, c Check) string {
	return fmt.Sprintf("ALTER DOMAIN %s ADD CONSTRAINT %s %s", t.ID(), QuoteIdent(c.Name), c.Definition)
}

func createSequenceSQL(s Sequence) string {
	cycle := "NO CYCLE"
	if s.Cycle {
		cycle = "CYCLE"
	}
	return fmt.Sprintf("CREATE SEQUENCE %s AS %s START WITH %d INCREMENT BY %d MINVALUE %d MAXVALUE %d CACHE %d %s",
		s.ID(), s.DataType, s.Start, s.Increment, s.Min, s.Max, s.Cache, cycle)
}

func columnSQL(c Column) string {
	var b strings.Builder
	b.WriteString(QuoteIdent(c.Name) + " " + c.Type)
	if c.Collation != "" {
		b.WriteString(" COLLATE " + c.Collation)
	}
	switch {
	case c.Generated == "stored":
		b.WriteString(" GENERATED ALWAYS AS (" + c.Default + ") STORED")
	case c.Generated == "virtual":
		b.WriteString(" GENERATED ALWAYS AS (" + c.Default + ") VIRTUAL")
	case c.Identity == "always":
		b.WriteString(" GENERATED ALWAYS AS IDENTITY")
	case c.Identity == "by default":
		b.WriteString(" GENERATED BY DEFAULT AS IDENTITY")
	case c.Default != "":
		b.WriteString(" DEFAULT " + c.Default)
	}
	if c.NotNull {
		b.WriteString(" NOT NULL")
	}
	return b.String()
}

// createTableSQL creates a table with its columns. A partition takes its
// columns from the parent; parent is nil for anything else.
func createTableSQL(t Table, parent *Table) []string {
	var b strings.Builder
	b.WriteString("CREATE ")
	if t.Unlogged {
		b.WriteString("UNLOGGED ")
	}
	b.WriteString("TABLE " + t.ID())
	var after []string
	if t.PartitionOf != "" {
		b.WriteString(" PARTITION OF " + t.PartitionOf + " " + t.PartitionBound)
		if parent != nil {
			after = partitionColumnSQL(t, *parent)
		}
	} else {
		cols := make([]string, len(t.Columns))
		for i, c := range t.Columns {
			cols[i] = "\n  " + columnSQL(c)
		}
		b.WriteString(" (" + strings.Join(cols, ",") + "\n)")
	}
	if t.Partitioned {
		b.WriteString(" PARTITION BY " + t.PartitionKey)
	}
	if len(t.Options) > 0 {
		b.WriteString(" WITH (" + strings.Join(t.Options, ", ") + ")")
	}
	return append([]string{b.String()}, after...)
}

// partitionColumnSQL sets the defaults and NOT NULLs where a partition's
// column differs from its parent's.
func partitionColumnSQL(t, parent Table) []string {
	var stmts []string
	for _, c := range t.Columns {
		p := parent.Column(c.Name)
		if p == nil || c.Generated != "" || c.Identity != "" {
			continue
		}
		col := t.ID() + " ALTER COLUMN " + QuoteIdent(c.Name)
		if c.Default != p.Default {
			if c.Default == "" {
				stmts = append(stmts, "ALTER TABLE "+col+" DROP DEFAULT")
			} else {
				stmts = append(stmts, "ALTER TABLE "+col+" SET DEFAULT "+c.Default)
			}
		}
		if c.NotNull && !p.NotNull {
			stmts = append(stmts, "ALTER TABLE "+col+" SET NOT NULL")
		}
	}
	return stmts
}

func createViewSQL(v View, orReplace bool) string {
	kind := "VIEW"
	if v.Materialized {
		kind = "MATERIALIZED VIEW"
	}
	verb := "CREATE "
	if orReplace && !v.Materialized {
		verb = "CREATE OR REPLACE "
	}
	opts := ""
	if len(v.Options) > 0 {
		opts = " WITH (" + strings.Join(v.Options, ", ") + ")"
	}
	stmt := verb + kind + " " + v.ID() + opts + " AS\n" + v.Definition
	if v.Materialized {
		stmt += "\nWITH NO DATA"
	}
	return stmt
}

func addConstraintSQL(c Constraint) string {
	return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s %s", c.Table, QuoteIdent(c.Name), c.Definition)
}

func triggerSQL(t Trigger) []string {
	stmts := []string{t.Definition}
	on := "ALTER TABLE " + t.Table + " "
	switch t.Enabled {
	case "disabled":
		stmts = append(stmts, on+"DISABLE TRIGGER "+QuoteIdent(t.Name))
	case "replica":
		stmts = append(stmts, on+"ENABLE REPLICA TRIGGER "+QuoteIdent(t.Name))
	case "always":
		stmts = append(stmts, on+"ENABLE ALWAYS TRIGGER "+QuoteIdent(t.Name))
	}
	return stmts
}

func rlsSQL(t Table) []string {
	var stmts []string
	if t.RLSEnabled {
		stmts = append(stmts, "ALTER TABLE "+t.ID()+" ENABLE ROW LEVEL SECURITY")
	}
	if t.RLSForced {
		stmts = append(stmts, "ALTER TABLE "+t.ID()+" FORCE ROW LEVEL SECURITY")
	}
	return stmts
}

func createPolicySQL(p Policy) string {
	mode := "PERMISSIVE"
	if !p.Permissive {
		mode = "RESTRICTIVE"
	}
	roles := make([]string, len(p.Roles))
	for i, r := range p.Roles {
		roles[i] = roleSQL(r)
	}
	stmt := fmt.Sprintf("CREATE POLICY %s ON %s AS %s FOR %s TO %s", QuoteIdent(p.Name), p.Table, mode, p.Command, strings.Join(roles, ", "))
	if p.Using != "" {
		stmt += " USING (" + p.Using + ")"
	}
	if p.WithCheck != "" {
		stmt += " WITH CHECK (" + p.WithCheck + ")"
	}
	return stmt
}

func roleSQL(role string) string {
	if role == "PUBLIC" {
		return role
	}
	return QuoteIdent(role)
}

// grantTarget renders the ON clause of a GRANT or REVOKE.
func grantTarget(g Grant) (privilege, target string) {
	switch g.ObjectKind {
	case ObjectColumn:
		table, column, _ := cutLast(g.Object)
		return g.Privilege + " (" + column + ")", "TABLE " + table
	case ObjectFunction:
		// ROUTINE covers functions and procedures alike.
		return g.Privilege, "ROUTINE " + g.Object
	default:
		return g.Privilege, strings.ToUpper(string(g.ObjectKind)) + " " + g.Object
	}
}

func grantSQL(g Grant) string {
	priv, target := grantTarget(g)
	stmt := fmt.Sprintf("GRANT %s ON %s TO %s", priv, target, roleSQL(g.Grantee))
	if g.Grantable {
		stmt += " WITH GRANT OPTION"
	}
	return stmt
}

func revokeSQL(g Grant) string {
	priv, target := grantTarget(g)
	return fmt.Sprintf("REVOKE %s ON %s FROM %s", priv, target, roleSQL(g.Grantee))
}

// when runs stmt only if cond holds, for guards Postgres has no IF [NOT]
// EXISTS for.
func when(cond, stmt string) string {
	return "DO $dbproof$ BEGIN IF " + cond + " THEN " + stmt + "; END IF; END $dbproof$"
}

// unlessExists runs stmt only when query finds no row.
func unlessExists(query, stmt string) string {
	return when("NOT EXISTS ("+query+")", stmt)
}

func ifNotExistsSQL(on bool) string {
	if on {
		return "IF NOT EXISTS "
	}
	return ""
}

func ifExistsSQL(on bool) string {
	if on {
		return "IF EXISTS "
	}
	return ""
}
