package schema_test

import (
	"slices"
	"strings"
	"testing"

	"github.com/borovikovd/dbproof-agent/internal/pgtest"
	"github.com/borovikovd/dbproof-agent/schema"
)

// TestDriftDDL follows what DbProof does with drift: production changes
// outside migrations, the server diffs the two captures, and offers
//   - an adopt migration (guarded DDL) that must turn a fresh replay of the
//     old schema into the new one, and do nothing where production already
//     has the change;
//   - revert SQL (reverse DDL) that must turn production back.
func TestDriftDDL(t *testing.T) {
	cases := []struct {
		name, setup, change string
		// irreversible is set when Postgres can't undo the change, and the
		// revert SQL must say so instead.
		irreversible bool
	}{
		{
			name:   "a serial column added in production",
			setup:  `CREATE TABLE orders (id bigint PRIMARY KEY, total numeric NOT NULL);`,
			change: `ALTER TABLE orders ADD COLUMN seq serial;`,
		},
		{
			name:   "a table with a serial key created in production",
			setup:  `CREATE TABLE orders (id bigint PRIMARY KEY);`,
			change: `CREATE TABLE refunds (id serial PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders);`,
		},
		{
			name:  "a reporting view built on a new view",
			setup: `CREATE TABLE orders (id bigint PRIMARY KEY, total numeric NOT NULL, placed_at timestamptz NOT NULL);`,
			change: `CREATE VIEW order_totals AS SELECT id, total FROM orders;
				CREATE VIEW big_orders AS SELECT id FROM order_totals WHERE total > 100;`,
		},
		{
			name:  "a table and a function returning its rows created in production",
			setup: `CREATE TABLE orders (id bigint PRIMARY KEY);`,
			change: `CREATE TABLE refunds (id bigint PRIMARY KEY, amount numeric NOT NULL);
				CREATE FUNCTION big_refunds() RETURNS SETOF refunds LANGUAGE sql STABLE AS $$ SELECT * FROM refunds WHERE amount > 100 $$;`,
		},
		{
			name:         "an enum value added at the front",
			setup:        `CREATE TYPE order_status AS ENUM ('paid', 'shipped'); CREATE TABLE orders (id bigint PRIMARY KEY, status order_status);`,
			change:       `ALTER TYPE order_status ADD VALUE 'pending' BEFORE 'paid';`,
			irreversible: true,
		},
		{
			name: "a column added to a partitioned table",
			setup: `CREATE TABLE events (id bigint NOT NULL, at timestamptz NOT NULL) PARTITION BY RANGE (at);
				CREATE TABLE events_2026_09 PARTITION OF events FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
				CREATE TABLE events_2026_10 PARTITION OF events FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');`,
			change: `ALTER TABLE events ADD COLUMN source text;`,
		},
		{
			name:   "a serial key switched to identity",
			setup:  `CREATE TABLE orders (id serial PRIMARY KEY, total numeric);`,
			change: `ALTER TABLE orders ALTER COLUMN id DROP DEFAULT; DROP SEQUENCE orders_id_seq; ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;`,
		},
		{
			name: "a view narrowed in production",
			setup: `CREATE TABLE orders (id bigint PRIMARY KEY, total numeric, note text);
				CREATE VIEW order_list AS SELECT id, total, note FROM orders;
				GRANT SELECT ON order_list TO PUBLIC;`,
			change: `DROP VIEW order_list; CREATE VIEW order_list AS SELECT id, total FROM orders; GRANT SELECT ON order_list TO PUBLIC;`,
		},
		{
			name: "a materialized view redefined in production",
			setup: `CREATE TABLE orders (id bigint PRIMARY KEY, total numeric, placed_at date);
				CREATE MATERIALIZED VIEW daily_sales AS SELECT placed_at, sum(total) AS total FROM orders GROUP BY placed_at;
				CREATE UNIQUE INDEX daily_sales_day ON daily_sales (placed_at);
				GRANT SELECT ON daily_sales TO PUBLIC;`,
			change: `DROP MATERIALIZED VIEW daily_sales;
				CREATE MATERIALIZED VIEW daily_sales AS SELECT placed_at, sum(total) AS total, count(*) AS orders FROM orders GROUP BY placed_at;
				CREATE UNIQUE INDEX daily_sales_day ON daily_sales (placed_at);
				GRANT SELECT ON daily_sales TO PUBLIC;`,
		},
	}
	for _, server := range pgtest.Servers(t) {
		for _, tc := range cases {
			t.Run(server.Name+"/"+tc.name, func(t *testing.T) {
				db := pgtest.NewDB(t, server)
				pgtest.Exec(t, db, tc.setup)
				before := inspect(t, db)
				pgtest.Exec(t, db, tc.change)
				after := inspect(t, db)
				changes := schema.Diff(before, after, schema.DiffOptions{})
				if len(changes) == 0 {
					t.Fatal("the change shows no drift")
				}
				t.Logf("drift:\n%s", describe(changes))

				// Adopt, in a fresh environment replaying migrations.
				replay := pgtest.NewDB(t, server)
				pgtest.Exec(t, replay, tc.setup)
				apply(t, replay, schema.ChangeDDL(changes, schema.DDLOptions{Guarded: true}))
				if left := schema.Diff(after, inspect(t, replay), schema.DiffOptions{}); len(left) > 0 {
					t.Errorf("adopt left differences on a replay:\n%s", describe(left))
				}

				// Adopt, in production, where the change already exists.
				apply(t, db, schema.ChangeDDL(changes, schema.DDLOptions{Guarded: true}))
				if left := schema.Diff(after, inspect(t, db), schema.DiffOptions{}); len(left) > 0 {
					t.Errorf("adopt changed production:\n%s", describe(left))
				}

				// Revert, in production.
				revert := schema.ChangeDDL(changes, schema.DDLOptions{Reverse: true})
				if tc.irreversible {
					if !slices.ContainsFunc(revert, func(s string) bool { return strings.HasPrefix(s, "-- ") }) {
						t.Errorf("revert doesn't say it can't undo the change:\n%s", strings.Join(revert, "\n"))
					}
					return
				}
				apply(t, db, revert)
				if left := schema.Diff(before, inspect(t, db), schema.DiffOptions{}); len(left) > 0 {
					t.Errorf("revert left differences:\n%s", describe(left))
				}
			})
		}
	}
}

// apply runs statements in order and fails the test at the first error.
func apply(t *testing.T, dbURL string, stmts []string) {
	t.Helper()
	conn := pgtest.Connect(t, dbURL)
	for _, stmt := range stmts {
		if _, err := conn.Exec(t.Context(), stmt); err != nil {
			t.Fatalf("%v\n%s", err, stmt)
		}
	}
}
